### ISSUE TITLE
combineRIP function does not filter

### ISSUE THREAD

**Issue by adomingues** [yueli-compbio/RIPSeeker#1]
Hi @yueli-compbio,

I am using RIPSeeker on a set of experiments with biological replicates, 1st running `ripSeek`without any filtering options set, and then merging the peaks using `combineRIP`. At this second point I was applying an `FDR` cut-off but noticed that this had no effect on the number of peaks. After some testing, it seems like no peaks have having a flag set to `FALSE` and thus this [line](https://github.com/yueli-compbio/RIPSeeker/blob/master/R/combineRIP.R#L32) always returns the same number of peaks as the input. 

Replacing the cutoff rules from `combineRIP`

```r
cutoff <- 
		
			if(!is.null(values(gr)$logOddScore)) 
				values(gr)$logOddScore >= logOddCutoff else TRUE &
			
			if(!is.null(values(gr)$pval))
				values(gr)$pval <= pvalCutoff else TRUE &
			
			if(!is.null(values(gr)$pvalAdj))
				values(gr)$pvalAdj <= pvalAdjCutoff else TRUE &
			
			if(!is.null(values(gr)$eFDR))
values(gr)$eFDR <= eFDRCutoff else TRUE
```
 with the equivalent (modified) code from `seekRIP` does the trick:

```
      function(x) {
         gr <- as(import(x), "GRanges")
         print(length(gr))   
         # construct cutoff rule
         cutoff <- 
            values(gr)$logOddScore >= logOddCutoff &
            values(gr)$pval <= pvalCutoff &
            values(gr)$pvalAdj <= pvalAdjCutoff &
            values(gr)$eFDR <= eFDRCutoff
         
         gr[cutoff]
```

For now this hack will do with my purposes, but I thought you should know about this.

Cheers.

**Comment by adomingues** [comment]
I decided to go ahead an issue an fix in case it makes your life easier. Fell free to reject it.

**Comment by yueli-compbio** [comment]
Thanks. I agree with the change. My apologies for the confusion.

**Comment by adomingues** [comment]
No worries, bugs will happen and are there to be fixed :) 

I hope the[ pull request](https://github.com/yueli-compbio/RIPSeeker/pull/2) has an adequate fix. It worked with my test data.
